let initialized=false,suggested=[],lastState={};const $=id=>document.getElementById(id);
const api=async(path,options={})=>{const r=await fetch(path,options),j=await r.json();if(!r.ok)throw Error(j.error||'请求失败');return j};
const split=v=>v.split(/[，,\n]/).map(x=>x.trim()).filter(Boolean);
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active');$('title').textContent={home:'今日概览',search:'搜索与匹配',chat:'沟通与 AI',data:'数据与恢复'}[b.dataset.view]});
async function saveConfig(silent=false){try{await api('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({keywords:split($('keywords').value),max_pages:+$('pages').value,min_salary:+$('salary').value,workers:+$('workers').value,greeting:$('greeting').value.trim(),exclude:split($('exclude').value),blacklist:split($('blacklist').value),resume_general:$('resumeGeneral').value.trim(),resume_ai:$('resumeAi').value.trim(),resume_data:$('resumeData').value.trim(),deepseek_enabled:$('deepseekEnabled').checked,preferences:$('preferences').value.trim()})});if(!silent)alert('设置已保存');return true}catch(e){alert(e.message);return false}}
async function run(action){if(!await saveConfig(true))return;try{await api('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})})}catch(e){alert(e.message)}}
async function resumeRun(){try{await api('/api/resume',{method:'POST'})}catch(e){alert(e.message)}}
async function stopRun(){try{await api('/api/stop',{method:'POST'})}catch(e){alert(e.message)}}
async function abortRun(){if(confirm('立即停止？已保存的搜索和沟通断点会保留。'))try{await api('/api/abort',{method:'POST'})}catch(e){alert(e.message)}}
function showHelp(){$('help').showModal()} function useSuggestions(){$('keywords').value=suggested.join('\n')}
async function poll(){try{const s=await api('/api/state');lastState=s;$('badge').textContent=s.running?'运行中':'系统就绪';['stage','total','pending','success','quota'].forEach(k=>$(k).textContent=s[k]);$('activeModules').textContent=s.active_actions.length?'运行模块：'+s.active_actions.map(x=>({scan:'搜索',communicate:'沟通',watch:'监听',check:'单次检查',profile:'简历同步',full:'完整流程'}[x]||x)).join('、'):'当前无运行模块';$('interview').classList.toggle('hidden',!s.interview_alerts);suggested=s.config.suggestions||[];$('suggestions').textContent=suggested.join('、')||'尚无简历快照';$('recoveryText').textContent=s.recovery.resumable?`可恢复：${s.recovery.label}`:'没有待恢复任务';$('resumeBtn').classList.toggle('hidden',!s.recovery.resumable);$('paths').innerHTML=Object.entries(s.paths).map(([k,v])=>`<div><b>${k}</b><br>${v}</div>`).join('');$('matchMethod').textContent=`岗位筛选：${s.matching.method}，阈值 ${s.matching.threshold} 分。DeepSeek：${s.matching.deepseek_role}。`;$('greetingPreview').innerHTML=s.greeting_previews.length?s.greeting_previews.map(x=>`<div><b>${x.job}${x.company?' · '+x.company:''}</b><span class="${x.personalized?'ai':'fallback'}">${x.personalized?'AI 个性化':'默认备用'}</span><p>${x.greeting}</p></div>`).join(''):'搜索完成后在这里显示前 8 条实际待发送文案。';const box=$('log'),bottom=box.scrollHeight-box.scrollTop-box.clientHeight<40;box.textContent=s.logs.join('\n')||'等待操作…';if(bottom)box.scrollTop=box.scrollHeight;if(!initialized){const c=s.config;$('keywords').value=c.keywords.join('\n');$('pages').value=c.max_pages;$('salary').value=c.min_salary;$('workers').value=c.workers;$('greeting').value=c.greeting;$('exclude').value=c.exclude.join(', ');$('blacklist').value=c.blacklist.join(', ');$('resumeGeneral').value=c.resume_general;$('resumeAi').value=c.resume_ai;$('resumeData').value=c.resume_data;$('deepseekEnabled').checked=c.deepseek_enabled;$('preferences').value=c.preferences;initialized=true}}catch(e){$('badge').textContent='连接失败'}setTimeout(poll,1200)}poll();
